### ISSUE TITLE
64: dust

### ISSUE THREAD

**Issue by cryptozeny** [sugarchain-project/web-wallet#1]
if i send `1 sat`, i got error. i understand banning this dust. my question is whats the dust limit?

![image](https://user-images.githubusercontent.com/37016180/71597821-fdfcbd80-2b87-11ea-997e-0521e14e804b.png)

![image](https://user-images.githubusercontent.com/37016180/71597776-da397780-2b87-11ea-8e68-11c77ab2cd11.png)

**Comment by cryptozeny** [comment]
same error with
2 sat
4 sat
8 sat
16 sat
32 sat
64 sat
128 sat
256 sat

but `512sat` sent OK
https://sugar.wtf/#/transaction/25c0ef40d4189cf7728a96ea0d2d01fd315fbb94154b7d2b15da66e57f4a107b

**Comment by cryptozeny** [comment]
294 sat : OK this is the LIMIT
https://sugar.wtf/#/transaction/e446935e109e6c9359ddb4ca70d163cfe5a0005cb455b09b11e1ddfea8a91adb
https://sugar.wtf/#/transaction/deaeb2c0b49f1aa488e09a22db03e116906747152efe2c6d82c03bc2e27dd9fd

but 293 not possible.

**Comment by cryptozeny** [comment]
however i suggest minimum Transfer Limit is: 
`at least 1 SUGAR` against dust attack. current is `0.00000294 SUGAR`

and Fee is:
at least `0.0001 SUGAR` 10x than current one.
@volbil

**Comment by cryptozeny** [comment]
https://github.com/sugarchain-project/sugarchain/blob/master-v0.16.3/src/policy/policy.cpp#L52-L55

**Comment by cryptozeny** [comment]
https://github.com/sugarchain-project/sugarchain/blob/master-v0.16.3/src/policy/policy.cpp#L20-L33

**Comment by volbil** [comment]
This is Yumekawa related issue.
