### ISSUE TITLE
Stuck at loading funds 

### ISSUE THREAD

**Issue by mars432** [sugarchain-project/web-wallet#10]
![IMG_20210524_100611](https://user-images.githubusercontent.com/84706085/119317413-5b5f4600-bc78-11eb-844c-5fa40884fd8b.jpg)

**Comment by taph777** [comment]
facing the same issue here

**Comment by mars432** [comment]
Yea what exactly should we do now ?

**Comment by taph777** [comment]
''Api node is currently loading block index,it may take some time''
Thats the telegram reply i got,we just have to wait for it then

**Comment by mars432** [comment]
Thank you mate

**Comment by decryp2kanon** [comment]
it seems just server side hw failure. (node down) will fixed soon. @volbil

**Comment by mars432** [comment]
I hope so

**Comment by mars432** [comment]
Well it is working again !! Thank you guys for responses !!

**Comment by c3rb1** [comment]
why i cant send funds ???  its says Loading  UTXOs...
