### ISSUE TITLE
WIF imported send fail

### ISSUE THREAD

**Issue by cryptozeny** [sugarchain-project/web-wallet#2]
> aglkmToday at 10:56 PM
> So, I did: 1) open by key 2) generate 3) create. Then return to open by key tab and paste the private key, then I deposited and then tried to send, but that was never successful
i tried and this problem. @aglkm#2786 @volbil#8559

![image](https://user-images.githubusercontent.com/37016180/71766772-fa31b800-2f46-11ea-83cd-df8f8fa773eb.png)

i guess imported WIF wallet has sending issue.
@aglkm you seems right. WIF imported wallet not worked to me.

**Comment by cryptozeny** [comment]
i tested @aglkm WIF, but it worked to me.
![image](https://user-images.githubusercontent.com/37016180/71766962-7f1dd100-2f49-11ea-9a4e-46131269896c.png)
![image](https://user-images.githubusercontent.com/37016180/71766976-952b9180-2f49-11ea-9779-924089d38073.png)

![image](https://user-images.githubusercontent.com/37016180/71766960-79c08680-2f49-11ea-8f3e-46859935c28e.png)

weired

**Comment by volbil** [comment]
Should be fixed in https://github.com/sugarchain-project/web-wallet/pull/3
